[package]
name = "bedelibry-prolog-runtime-rs"
version = "0.1.0"
authors = ["Nathan Bedell <nbedell@tulane.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdo = "0.3.0"
derive_more = "0.99.0"